// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-heroes/Care.tsx": () => import("../components/mockups/landing-heroes/Care.tsx"),
  "./components/mockups/landing-heroes/CareV2.tsx": () => import("../components/mockups/landing-heroes/CareV2.tsx"),
  "./components/mockups/landing-heroes/CareV3.tsx": () => import("../components/mockups/landing-heroes/CareV3.tsx"),
  "./components/mockups/landing-heroes/MedSpa.tsx": () => import("../components/mockups/landing-heroes/MedSpa.tsx"),
  "./components/mockups/landing-heroes/MedSpaV2.tsx": () => import("../components/mockups/landing-heroes/MedSpaV2.tsx"),
  "./components/mockups/landing-heroes/MedSpaV3.tsx": () => import("../components/mockups/landing-heroes/MedSpaV3.tsx"),
  "./components/mockups/landing-heroes/Wellness.tsx": () => import("../components/mockups/landing-heroes/Wellness.tsx"),
  "./components/mockups/landing-heroes/WellnessV2.tsx": () => import("../components/mockups/landing-heroes/WellnessV2.tsx"),
  "./components/mockups/landing-heroes/WellnessV3.tsx": () => import("../components/mockups/landing-heroes/WellnessV3.tsx"),
};
