// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-heroes/Care.tsx": () => import("../components/mockups/landing-heroes/Care.tsx"),
  "./components/mockups/landing-heroes/CareFullPage.tsx": () => import("../components/mockups/landing-heroes/CareFullPage.tsx"),
  "./components/mockups/landing-heroes/CareFullPageEnriched.tsx": () => import("../components/mockups/landing-heroes/CareFullPageEnriched.tsx"),
  "./components/mockups/landing-heroes/CareV2.tsx": () => import("../components/mockups/landing-heroes/CareV2.tsx"),
  "./components/mockups/landing-heroes/CareV3.tsx": () => import("../components/mockups/landing-heroes/CareV3.tsx"),
  "./components/mockups/landing-heroes/CareV3Trust.tsx": () => import("../components/mockups/landing-heroes/CareV3Trust.tsx"),
  "./components/mockups/landing-heroes/CosmeticSurgeryV3.tsx": () => import("../components/mockups/landing-heroes/CosmeticSurgeryV3.tsx"),
  "./components/mockups/landing-heroes/DentalV3.tsx": () => import("../components/mockups/landing-heroes/DentalV3.tsx"),
  "./components/mockups/landing-heroes/FertilityV3.tsx": () => import("../components/mockups/landing-heroes/FertilityV3.tsx"),
  "./components/mockups/landing-heroes/HairClinicV3.tsx": () => import("../components/mockups/landing-heroes/HairClinicV3.tsx"),
  "./components/mockups/landing-heroes/HomecareClinical.tsx": () => import("../components/mockups/landing-heroes/HomecareClinical.tsx"),
  "./components/mockups/landing-heroes/HomecareEditorial.tsx": () => import("../components/mockups/landing-heroes/HomecareEditorial.tsx"),
  "./components/mockups/landing-heroes/HomecareWarm.tsx": () => import("../components/mockups/landing-heroes/HomecareWarm.tsx"),
  "./components/mockups/landing-heroes/IVTherapyV3.tsx": () => import("../components/mockups/landing-heroes/IVTherapyV3.tsx"),
  "./components/mockups/landing-heroes/LaserEyeV3.tsx": () => import("../components/mockups/landing-heroes/LaserEyeV3.tsx"),
  "./components/mockups/landing-heroes/MedSpa.tsx": () => import("../components/mockups/landing-heroes/MedSpa.tsx"),
  "./components/mockups/landing-heroes/MedSpaV2.tsx": () => import("../components/mockups/landing-heroes/MedSpaV2.tsx"),
  "./components/mockups/landing-heroes/MedSpaV3.tsx": () => import("../components/mockups/landing-heroes/MedSpaV3.tsx"),
  "./components/mockups/landing-heroes/PhysioV3.tsx": () => import("../components/mockups/landing-heroes/PhysioV3.tsx"),
  "./components/mockups/landing-heroes/TrustMarkersHero.tsx": () => import("../components/mockups/landing-heroes/TrustMarkersHero.tsx"),
  "./components/mockups/landing-heroes/WeightManagementV3.tsx": () => import("../components/mockups/landing-heroes/WeightManagementV3.tsx"),
  "./components/mockups/landing-heroes/Wellness.tsx": () => import("../components/mockups/landing-heroes/Wellness.tsx"),
  "./components/mockups/landing-heroes/WellnessV2.tsx": () => import("../components/mockups/landing-heroes/WellnessV2.tsx"),
  "./components/mockups/landing-heroes/WellnessV3.tsx": () => import("../components/mockups/landing-heroes/WellnessV3.tsx")
};
