// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-heroes/Care.tsx": () => import("../components/mockups/landing-heroes/Care.tsx"),
  "./components/mockups/landing-heroes/MedSpa.tsx": () => import("../components/mockups/landing-heroes/MedSpa.tsx"),
  "./components/mockups/landing-heroes/Wellness.tsx": () => import("../components/mockups/landing-heroes/Wellness.tsx")
};
